name: test

on:
  push:
    branches: [ d20 ]
  pull_request:
    branches: [ d20 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            packages/*/package-lock.json

      - name: Bootstrap
        run: npm run bootstrap

      - name: Run test
        run: npm run test

      - name: Collect coverage
        run: npx codecov
