name: test

on:
  push:
    branches: [ d20 ]
  pull_request:
    branches: [ d20 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: npm run bootstrap

      - name: Run test
        run: npm run test

      - name: Collect coverage
        run: npx codecov
